Support limits
topclaudy/compoships pull request #180
Opened 2024-11-17 22:52 UTC by parkourben99

Fixed https://github.com/topclaudy/compoships/issues/173

First attempt to support sub query limits

example:
```
User::with([
    'posts' => fn ($query) => $query->limit(3)
])->paginate();
```

2024-11-20 14:32 UTC, parallels999 commented
https://github.styleci.io/analyses/EP1env

2024-11-20 23:10 UTC, parkourben99 commented
> https://github.styleci.io/analyses/EP1env

Not a very helpful comment. This PR is marked as draft as it's still being tested and validated.

2025-01-09 13:33 UTC, parallels999 commented on composer.json
> +    "laravel/serializable-closure": "^1.3|^2.0"
>However, the Laravel version constraint in your composer.json file would restrict compatibility with those versions.

Remove this line
```diff
-"illuminate/database": "^11.0",
-"laravel/serializable-closure": "^1.3|^2.0"
+"illuminate/database": ">=5.6 <12.0"

```

2025-01-10 22:55 UTC, parkourben99 commented
> Hi @parkourben99 Thank you for the PR! This package is designed to support Laravel versions prior to 11. However, the Laravel version constraint in your composer.json file would restrict compatibility with those versions.

I'm not sure these changes will work with previous versions of laravel, due to the recent change in laravel to support limits.

Do the tests run on previous versions?

2025-01-15 19:42 UTC, parallels999 commented on tests/Unit/LimitTest.php
> +    {
>I'm not sure these changes will work with previous versions of laravel

Add something like this
```php
if (getLaravelVersion() < 11.0) {
    $this->markTestIncomplete('This test is broken on laravel 10.x and earlier!');
}
```
https://github.com/topclaudy/compoships/blob/9b37b516a586a751e041b58672ff618a0e57492e/tests/ComposhipsTest.php#L266-L268

2025-03-04 00:49 UTC, mpyw commented
@parkourben99 @parallels999 Any updates? I'm going to abandon https://github.com/mpyw/compoships-eager-limit. I'm looking forward to this PR get merged!

2025-03-04 01:01 UTC, parkourben99 commented
> @parkourben99 @parallels999 Any updates? I'm going to abandon https://github.com/mpyw/compoships-eager-limit. I'm looking forward to this PR get merged!

Apologises, I have updated this PR.

2025-03-05 10:02 UTC, mpyw commented
@topclaudy @parallels999 We'll appreciate if you review this in your free time 😃

2025-03-05 13:50 UTC, parallels999 commented
I am not the maintainer of this package, I don't know why you ask me for a review, At most I avoid being left without support in my old apps

2025-03-21 15:03 UTC, chrispappas commented
@parkourben99 I just submitted a PR into your PR 🤯 https://github.com/parkourben99/compoships/pull/1

Your changes are not backwards-compatible with older PHP versions, GH Actions test matrix was failing, so I updated the code to use older switch and function closures. Tests are passing now on my fork of your fork.

2025-03-21 15:59 UTC, erikn69 commented on src/Compoships.php
> +            default  => throw new RuntimeException('This database is not supported.'),
Does `MariaDbGrammar` support this feature??

[Illuminate/Database/DatabaseManager.php#L407-L410](https://github.com/laravel/framework/blob/67286590127b8531b661a85e17c0a39d12030429/src/Illuminate/Database/DatabaseManager.php#L407-L410)
[Illuminate/Database/Query/Grammars/MariaDbGrammar.php](https://github.com/laravel/framework/blob/12.x/src/Illuminate/Database/Query/Grammars/MariaDbGrammar.php)

2025-03-22 11:56 UTC, parkourben99 commented
> @parkourben99 I just submitted a PR into your PR 🤯 [parkourben99#1](https://github.com/parkourben99/compoships/pull/1)
> 
> Your changes are not backwards-compatible with older PHP versions, GH Actions test matrix was failing, so I updated the code to use older switch and function closures. Tests are passing now on my fork of your fork.

Thanks @chrispappas not sure why dead versions of PHP are still being supported

2025-03-22 11:58 UTC, parkourben99 commented on src/Compoships.php
> +            default  => throw new RuntimeException('This database is not supported.'),
MariaDB grammar is just extending mysql grammar so it could be added here too. Feel free to add it.

2025-04-04 14:15 UTC, chrispappas commented
@parkourben99 the linting issue failing the CI build was introduced in my PR (sorry eh 🍁), can you fix please? I'd love to get this PR landed so I can switch back to using the main repo for compoships, and not my personal fork

2025-04-14 14:09 UTC, chrispappas commented
@topclaudy just a follow-up ping on this PR for review, when you have time. I have been using my forked branch with this change in prod for the last few weeks and it works as expected.

2025-04-14 17:52 UTC, topclaudy commented
@parkourben99 Can you please fix the failing tests?

2025-04-14 18:01 UTC, parallels999 commented on src/Compoships.php
> +            default  => throw new RuntimeException('This database is not supported.'),
`mariadb` users will get `RuntimeException('This database is not supported.'),`

2025-04-14 23:28 UTC, parkourben99 commented
> @parkourben99 Can you please fix the failing tests?

Looks like the failing test are due to backed enums. I have merged master into this PR.

@parallels999 I've also added support for mariadb

2025-04-15 08:01 UTC, topclaudy commented
@parkourben99 Thanks for the update. The tests are still failing tough. Can you take a look when you have a moment?

2025-04-15 16:44 UTC, topclaudy commented
@parkourben99 The tests are green on `master` https://github.com/topclaudy/compoships/commit/41e7979ddc25314a18f2e71b77afcd8a013a6fff

2025-08-27 13:52 UTC, parkourben99 commented
Hi @topclaudy apologies I forgot to push my code, tests should now be all working.

2025-09-07 20:25 UTC, chrispappas requested changes

2025-09-07 20:25 UTC, chrispappas commented on composer.json
> +    "phpunit/phpunit": "^6.0|^8.0|^9.0|^10.0|^11.0||^12.0"
This should just be a single pipe character

2025-09-07 23:15 UTC, parkourben99 commented on composer.json
> +    "phpunit/phpunit": "^6.0|^8.0|^9.0|^10.0|^11.0||^12.0"
Thanks Chris.

2025-10-03 11:13 UTC, merged

2025-10-03 11:14 UTC, topclaudy commented
Thanks @parkourben99 !